### ISSUE TITLE
Automatically mark Github milestone as complete

### ISSUE THREAD

**Issue by chillu** [silverstripe/cow#1]

**Comment by tractorcow** [comment]
Aw, I saw your title and was excited to see the code you'd written. :)

**Comment by robbieaverill** [comment]
Potentially this is now more relevant (for SilverStripe Ltd) to target ZenHub releases rather than GitHub. My team uses GitHub milestones for sprints for example, because ZenHub doesn't provide us any other way to track them. We'd use a ZenHub release instead e.g. https://app.zenhub.com/workspaces/creative-commoners-59ee915fe6bae8586525b9ef/reports/release?release=5a3b11fe4e60896aac59f391

**Comment by Cheddam** [comment]
The CMS Squad tracks work that happens after the tags are published within the ZenHub / GitHub milestone, such as communications, so I don't think this feature makes sense in the context of our current processes.
