### ISSUE TITLE
Allow specifying a prior release when creating a new release

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/cow#133]
When creating a new release with Cow it'd be nice to be able to set a prior release to set prior versions of modules in the plan. For example when releasing `2.3.0` we can set the prior release to `2.2.2` which will inspect the composer.json for that release and set prior versions in the new plan.

#### Proposed syntax:
```
cow release:create 2.3.0 cwp/cwp-recipe-kitchen-sink -vvv --prior-release 2.2.2
```

**Comment by Cheddam** [comment]
Arguably this has been superseded by the automatic prior version detection in #143, so I'll close this out for now.

**Comment by robbieaverill** [comment]
Let's argue =D I'm not sure #143 would fulfil the A/C of being able to say the previous release should be 2.2.2 for a new release of 2.3.0, given that there may be existing releases 2.2.3 and 2.2.4 in between.

"Why would you want to do that?" I hear you ask. Probably only for changelogs, and at that; changelogs that you have to generate because you messed something up in between releases. You can still manually adjust individual modules and recipe prior versions if needed, so that one reason on its own is probably not enough to keep this open. 👍

**Comment by Cheddam** [comment]
Yep, agree there is more nuance to this issue than what #143 covered, but needing to specify a previous release that isn't actually the previous release is an edgecase. I think if we were to reopen this issue we'd want to narrow the description, provide a clear case of when this has been necessary and weigh up the cost of manually resolving the situation vs. adding more functionality to Cow.

**Comment by robbieaverill** [comment]
Totally, and the last thing you need is more open issues
