### ISSUE TITLE
Is the '--' in Cow commands needed?

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cow#176]
Reported following the recent RC tag:

Was getting errors with all cow commands ( don't think the ' - - ' is needed?) - looks like the docs say to use the wrong commands.

- Update the docs to ensure the ordering of the arguments are correct. (Serge knows what to do)

**Comment by dhensby** [comment]
the `--` where? before option names or between options and arguments?

the double hyphen is usually used to disambiguate between options (`--an-option`) which can optionally have arguments and when the arguments start. eg: `cow moo --option-with-possible-arg -- argument` and `cow moo --option-with-possible-arg optional -- argument`. In the first example, if the `--` is missing then the `argument` would be incorrectly parsed as an argument to the option rather than to the command.

**Comment by brynwhyman** [comment]
Hey @dhensby will have to let @dnsl48 and @maxime-rainville chime in on that one, I've recorded the issue on their behalf :)

**Comment by dnsl48** [comment]
Yeah, that's not a problem with Cow, but rather our internal documentation. We have some docs putting an argument after `--`. I think we can move this issue into our internal repositories.

**Comment by brynwhyman** [comment]
Will do.

**Comment by brynwhyman** [comment]
Moved to https://github.com/silverstripeltd/product-issues/issues/205
