### ISSUE TITLE
Generate GitHub Releases with changelogs during tagging

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/cow#184]
Modules are released two ways:

- Automatically through Cow during quarterly releases
- Manually by hand on a case-by-case basis

When producing manual releases, we follow [a standard process](https://github.com/silverstripe/silverstripe-framework/pull/9626) of generating a changelog and creating a GitHub Release. Having a changelog at the module level is useful for developers who have 'critical dependencies' they need to keep track of updates to. However, Cow doesn't currently replicate this behaviour, instead pushing a simple tag and compiling a combined changelog to output at the recipe level.

We should make Cow mirror the manual release process, so that developers can always see the contents of individual module releases, whether they're generated by Cow or by hand.

This functionality is already baked into Cow, but it currently relies on the presence of Cow configuration in each individual module. This is cumbersome, so this issue should tackle either making the feature opt-out, or centralising the config.

## Acceptance criteria
- [x] When cow publishes a release, a matching release log is created for every new tag pushed to GitHub
- [x] The release description matches the default format generated by GitHub as closely as possible
- [x] Beta and RC create pre-release set to true

## Notes
- GitHub may have an API to do all of this for us and generate the description
- Maybe this doesn't need to be coupled with COW at all.
- Generating retroactive release description is out of scope.

## PRs
- https://github.com/silverstripe/silverstripe-userforms/pull/1154
- ~~https://github.com/silverstripe/gha-tag-release/pull/8~~
- https://github.com/silverstripe/cow/pull/212

**Comment by dnsl48** [comment]
I just found out that Cow [actually supports](https://github.com/silverstripe/cow/blob/master/src/Steps/Release/PublishRelease.php#L224) publishing changelogs for modules too. Looks like we only have it set up for userforms at the moment.

We still need to think about the scenario of publishing a single module rather than the whole recipe.

**Comment by GuySartorelli** [comment]
userforms has its release added due to the configuration in https://github.com/silverstripe/silverstripe-userforms/blob/5/.cow.json

Ideally it should just be done for all repositories. The changelog can also be automatically generated for releases via the github API to match the way we do patch releases: https://docs.github.com/en/rest/releases/releases#generate-release-notes-content-for-a-release

**Comment by GuySartorelli** [comment]
I've decided to look into using github actions for this purpose - cow can continue adding the tags, and a github action on the repo will then create a release for that tag.

This means we can reuse the same functionality for creating releases for any semver-compatible tag that gets created.

**Comment by GuySartorelli** [comment]
Nevermind - it's been deemed too aggressive to do as a github action. Will do in cow.
