### ISSUE TITLE
Make release:translate non destructive

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cow#202]
Currently the `release:translate` command will remove any unused source keys 

When `tx push -s` is run, it will delete these unused source values from transifex.  I haven't tested this, though presumably it will also delete any corresponding translations.

**NOTE: It seems that unused source keys are retained, but there are some keys missing in transifex which get removed from the translation yml files.**

This will have an impact on older minor branches, specifically if we run `tx pull` during a patch release on an old minor branch, for instance for a security release.  In this scenario, there will be a translations regression e.g. keys and values in de.yml will be removed.

An unfortunate side effect of this is old irrelevant keys and values will clutter the source en.yml and translation de.yml in the current minor.  That's a trade off we need to take.

### ACs
- [ ] When running `cow release:translate`, unused keys are retained in all .yml and .json translation files

### PRs
- [ ] https://github.com/silverstripe/cow/pull/203

**Comment by GuySartorelli** [comment]
Looks like `tx pull` overrides the existing yaml content entirely. There is a mechanism in that command to check if the file is more recently updated than the transifex content, but we're overriding that to avoid the opposite problem where new translations wouldn't be pulled down.

`UpdateTranslations::transifexPullSource()` handles pulling that content down. This goes module by module, and pulls all translations in a single command.

My current thinking is that we should parse the yml prior to running the command, and keep the old content in memory. Then, after pulling, parse the newly-updated yml files, and merge the two together - any collisions will take the new content, but anything that got deleted can be merged back in. Then, if there are differences between the current file content and the newly-merged content, we can write it back down to the yml files.

**Comment by GuySartorelli** [comment]
Just summarizing a discussion Steve and I had on slack about this:

- The `i18nTextCollectorTask` isn't removing unused keys regardless of how it's run (via cow, via the browser, or via sake)
- By unused keys, for my investigation, this was keys I added to the .yml files that I knew weren't used anywhere. This is a more reliable method to know the key isn't being used than removing the usage of an existing key, as that may still be used elsewhere and therefore re-added by the task.
- cow will run with the 'merge' flag i.e. `dev/tasks/i18nTextCollectorTask "flush=all" "merge=1"`. The merge command, according to inline docs on i18nTextCollector.php is `merge: Merge new strings with existing ones already defined in language files (default: FALSE)`
  - Therefore cow is set to run that task non-destructively already, and my investigation shows the task works as expected in that manner.
- Based on the above, the `i18nTextCollectorTask` itself isn't (at least currently - maybe it was in the past) where keys are being dropped. There are keys missing in transifex (present in the .yml files) which will get dropped, which is where the current issue is.
- Steve's suggestion (which lines up with what I was thinking) is "maybe copy all the yml (and json?) files in cow to either memory or disk before tx pull, then merge them post pull"

**Comment by GuySartorelli** [comment]
Summary of a discussion @emteknetnz and I had on slack regarding sorting translations:
- Ideally, translations would be sorted alphabetically case insensitive.
  - e.g. "NavigateUp" should come before "NO_PREVIEW"
- I think it would be good for cow to set the correct sort order. There is some code to do this already for the json translations, though it currently isn't case insensitive and it's looking in the wrong place for `/src/en.js` instead of `.json` so it never actually happens.
- Starting to sort things in cow now would lead to some potentially messy PRs. Although theoretically after the initial release with the code change in cow the keys _should_ all be in the right order, any developer PRs where features are added that require new strings could add keys in the wrong order.
- Steve:
> We've had SO much drama with translations in the past.  I'd personally had a to go through ALL the translations commits a couple of times due to regressions happening.  If we end up with commits where it's a combinations of
> a) new translations from tx pull
> b) sorting
> it's going to be a nightmare to diagnose if anything went wrong
> so i think i've got a strong preference to not sorting at this stage
- Down the line once we've got more confidence that everything works the way we expect it to for translations we can look at adding sorting in pretty easily. For now, I'll remove the `ksort` line that would have (slightly incorrectly) sorted the json content.
