### ISSUE TITLE
Allow support for dual version constraints in recipes

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/cow#207]
We will support GraphQL v3 and v4 for some time. We want to be able to tag version like `~3.8.0 || ~4.0.0`

# Acceptance criteria
- [ ] There's a clear and documented way of adding dual version constraints in recipes
- [ ] Only one version of of the "dual supported version module" is tagged. The other version needs to be tagged manually.

# Notes
- We're not 100% sure what the best way of solving this is. We're thinking maybe the release manager can explicitly define what they want the recipe constraint to be. Whoever picks up tho card should take some time to define what their approach is and validate it with a colleague.

**Comment by maxime-rainville** [comment]
We decided this wasn't worth implementing because of secret reason.

**Comment by GuySartorelli** [comment]
This was originally closed because CMS 5 won't have dual constraints.
We are still supporting CMS 4 however and for a few releases now we've been using one-off hacks to allow the dual constraint for graphql.
This was brought up again in https://github.com/silverstripe/cow/pull/226, so I'm reopening this.

**Comment by GuySartorelli** [comment]
Closed, we have a way to do this for graphql which is the only dual-support module we have.
