### ISSUE TITLE
List pull requests instead of raw git changelog

### ISSUE THREAD

**Issue by chillu** [silverstripe/cow#67]
## Overview

We're listing full git commit logs for every release, across all modules. That's an extreme level of detail, particularly for major releases (and even minor releases). 

More importantly, the current commit log centric approach means that commits merged up from previous major release branches might be attributes to a wrong release. Consider this timeline:

 * Security fix in 3.x
 * Port of security fix in 4.x (separate commit)
 * 4.0.1 security release
 * Merge from 3.x to 4.x
 * 4.0.2 patch release

The security fix that's already gone out via 4.0.1 will pop up again in the 4.0.2 changelog because it's been merged up from 3.x

## Use Cases

 * Get an overview of a patch and minor release (anything worth upgrading for?). In particular, does this release contain security fixes. The security use case is already covered by the security mailinglist, which will tell you the required release numbers.
 * Tell devs that a particular bugfix made it into a release. While people can subscribe to issues and pull requests in github, they'll only find out when it's been closed/merged, not when it's been released. We usually close issues on merge, not on release.

There's a separate use case for API changes on major releases, but those are edited by hand.

# Proposal

 * Generate changelogs from pull request merges (e.g. through https://github.com/skywinder/Github-Changelog-Generator)
 * Include pull request merges from previous major release branches (assuming they've been merged up)
 * List issues related to these pull requests separately. 
 * Don't list commits, only point to pull requests (which might have multiple commits)
 * Link to Github commit list views for each module instead

# Notes

 * Issues which aren't related to pull requests might not be attributable to a major release line (unless they're referenced in commit messages?)

**Comment by tractorcow** [comment]
Yes sounds great. :)

**Comment by tractorcow** [comment]
@dhensby do you want to get a say on this?

I think getting a list of PRs from a branch (filtered up to the date of the prior tag) shouldn't be too hard.

**Comment by dhensby** [comment]
One concern with linking to PRs instead of commits themselves is that commits are permanent and GitHub PRs *could* not be. EG: we could move from GH to some other service in the distant future.

Could we provide links to the PR *and* the merge commit for that PR? Regarding sec fixes, there are no public PRs to link to, so how do we handle this? I think security releases are a bit of a distraction because they are quite exceptional. When I do a sec PR I merge the fix up from the lowest release rather than writing a fix per release because that makes tracking git history, PRs, (and potentially change logs) difficult but I'm aware that isn't "standard" and can lead to multiple commits all introducing the same fixes. We should probably have some special fix for security patches that doesn't unduly influence this decision.

Just for my own clarity, are we saying:

1. PR is merged into 3.5
2. PR is merged up into 3.6
3. Change log for next 3.5 and 3.6 patch releases will both include the link to PR / changelog entry?

if above is correct then I'm happy.

**Comment by tractorcow** [comment]
Something like:

 - [https://github.com/silverstripe/cow/pull/58](#58) API Upgrade to symfony 3 - [https://github.com/silverstripe/cow/pull/58/commits/8f72000c8a37e152426a3547d2e079848c01255b](8f72000)

**Comment by Cheddam** [comment]
Commit prefixes and what is included in our changelogs is being discussed further in an RFC: https://github.com/silverstripe/silverstripe-framework/issues/9687

For now we're retaining commits as the content for changelogs; the issue with duplicates caused by merge ups is generally handled by manual grooming during the release process, so is largely a non-issue at this point. I think this issue can be closed out for now.
