### ISSUE TITLE
Ensure that all commits are included in the changelogs, not just those with a prefix

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cow#88]
I suspect that commits without a prefix are ignored in the changelogs. We need to ensure that they are included, perhaps in a "Other changes" section at the bottom.

**Comment by maxime-rainville** [comment]
I'm not sure about this one. Sometimes there's minor stuff I probably wouldn't want in the change log that gets committed (e.g. Use `recipe-core` 4.3.x-dev in travis file).

I would rather keep the existing behavior. Or if we go ahead with this change, I would want a way to get some commits ignored.

**Comment by robbieaverill** [comment]
It’s important for security audits to show all changes

**Comment by robbieaverill** [comment]
It could be an optional thing perhaps? Open source changelogs could be abbreviated to only show API changes, enhancements and bug fixes, while the compiled CWP changelogs could include everything. Would that be better?

**Comment by dhensby** [comment]
This would make tidying up the commits of PRs quite important...

**Comment by robbieaverill** [comment]
Yeah I agree. We've internally got a lot of improvement with this I think anyway - I often log a file and see a bunch of "peer review updates" type commit messages =(

**Comment by flamerohr** [comment]
I used to clean up commits before merging them, squashing to chunks that make sense.
But yeah, I think everyone has their own styles of merging and handling pull requests.

**Comment by dhensby** [comment]
I try to as well, but some are huge, some are merged by non-core members and sometimes I'm on my phone...

**Comment by chillu** [comment]
I have some practical concerns about this: Git repo size. I wouldn't be surprised if changelogs make up >2MB of our `git clone` on framework. Git is smart about compression, but it's a lot of data even after compression and deduplication. If we need a full commit list as part of the audit record, I'd suggest we write this to a separate file which isn't committed as part of the codebase (and delivered to auditors instead).

On a related note, we can't use Github for this log view either, because it caps views at 250 commits, so even comparing between 4.1.0 and 4.2.0 minor releases blows up: https://github.com/silverstripe/silverstripe-framework/compare/4.1.0...4.2.0

**Comment by robbieaverill** [comment]
What about if we listed a bunch of GitHub release links instead of actual changelogs?

**Comment by chillu** [comment]
We could put this info into "releases" (rather than tags), which allow arbitrary content attached to them via Giithub, e.g. https://github.com/silverstripe/silverstripe-framework/releases. From memory, this attaches them as git commit metadata though, which would end up with the same result: A bloated repo.

**Comment by robbieaverill** [comment]
Time to move the docs out of framework then is it? 😉

**Comment by robbieaverill** [comment]
>From memory, this attaches them as git commit metadata though, which would end up with the same result: A bloated repo

We should try and validate this somehow- this option could be quite appealing

**Comment by sminnee** [comment]
Something to consider:

Should we push changelogs into the "releases" feature of github, and then produce recipe changelogs as an aggregation of all the package changelogs?

**Comment by robbieaverill** [comment]
I’m down, if it doesn’t have the same negative side effects @chillu mentioned above

**Comment by robbieaverill** [comment]
PR for discussion at #103
