### ISSUE TITLE
Releasing from RC with no patch branch tries to use minor branch

### ISSUE THREAD

**Issue by dhensby** [silverstripe/cow#90]
When trying to release 3.7.1 from 3.7.1-rc1 there was no 3.7.1 branch. cow tried to create the release from 3.7.x-dev instead which means bringing in commits that were not meant to make the 3.7.1 release.

If there's no patch branch we should fall back to the latest tag (ie: 3.7.1-rc1 in this case) if it exists for the release version we are aiming for...

**Comment by robbieaverill** [comment]
@tractorcow we had a brief chat about this and some other things this morning. Do you know why cow v2 doesn't create patch branches any more?

We were of a consensus that making patch branches is probably how this should behave by default (even if transparently creating a patch branch, merging and deleting it does nothing in most cases). This would mean we can tag security releases easily without releasing the rest of the patch changes in a minor release line too.

Do you have any thoughts about this?

**Comment by chillu** [comment]
Somewhat related: [RFC: Better handling of minor release branches](https://github.com/silverstripe/silverstripe-framework/issues/8257)

**Comment by tractorcow** [comment]
Because composer only worked with patch versions with self.version. This is because you'd install 3.7.1.x-dev, and the self.version would work all the way down the chain.

With the new cow you NEED the branch-alias for those branches. Because you don't have 3.7.1.x-dev in the branch-alias it wouldn't install.

The fix is to have cow make the branches, but then instead of relying on composer to "set" the right branch on install, you'd make cow reset them post-install. You'd also need to adjust the 'branching' option to support the patch branch.

Not terribly hard but it was done this way intentionally. The major motivation is that I was sick to death of deleting and merging those branches manually. And with 10+ modules multiplied by the number of releases, it was a huge maintenance burden.

Just so you know what you are getting yourself into. :)

**Comment by chillu** [comment]
We also need to ensure it uses the full git refs when referencing patch release branches vs. tags (they have the same "short name"). This tripped us up in the 4.2.0 release recently.

**Comment by Cheddam** [comment]
We've resolved this limitation by introducing the `release:checkout-tagged-base` command, which shifts the branches back to the last commit in common with the related release candidate (e.g. shifts to match `4.6.1-rc1` for the `4.6.1` release.) That approach has been working pretty well for us this year. Based on that, I don't think adjustments to support patch-level branches are necessary.
