### ISSUE TITLE
Release docs need a complete overhaul

### ISSUE THREAD

**Issue by dhensby** [silverstripe/cow#94]
The release docs https://docs.silverstripe.org/en/4/contributing/making_a_silverstripe_core_release/ are wrong and confusing

**Comment by tractorcow** [comment]
You need to describe what's wrong I think.

**Comment by chillu** [comment]
- `cow` needs to be run on an environment with the lowest supported PHP version, in order to avoid installing `>=php@7` dependencies. Dan said that `--ignore-platform-constraints` isn't feasible either, it doesn't installed the *lowest* version constraints
- When doing that, the VM needs to have git credentials set up properly, so we don't commit as anoymous users ([example](https://github.com/silverstripe/recipe-cms/commit/115bbbb5f98f98ea1f18f0d3ddb260a9328359be#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780)) - cc @dhensby ;)

**Comment by robbieaverill** [comment]
I think it would be better to review the existing pull requests that are open to update these docs than to track this here

* https://github.com/silverstripe/silverstripe-framework/pull/8298
* https://github.com/silverstripe/silverstripe-framework/pull/7681
